# Generated by Django 3.1.4 on 2020-12-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notefile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
