# Generated by Django 3.1.4 on 2020-12-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201226_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notefile', models.FileField(null=True, upload_to='mysite/media')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notefile',
        ),
    ]
